### ISSUE TITLE
Create a gif of bro explanation

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/bro_site#10]
It should be a chaotic viral rapid gif.

Use the following words and phrases:
It should be a chaotic viral rapid gif.

- I'm your bro
---
- I'm a validator
- Sustainable
- Freedom
- Open-source
- Responsible
---
- I'm a service provider
- Analytics
- Data
- Services
---
- I'm an ecosystem builder
- Community
- Governance
- Opinion
- Values 
---
- I'm relayer 
- Relaying 
- IBC
- Crosschain
---
and more...

**Comment by altbro** [comment]
My vision to keywords for gif:

I'm your Bro

----------------------------------

I'm validator
Reliable
Open-sourced
Responsible

----------------------------------

I'm provider
Analytics
Services
Relaying

----------------------------------

I develop ecosystem
Contributions
Values
Community

**Comment by altbro** [comment]
@irahunt please change animation for typing words to somehow faster
