### ISSUE TITLE
Provide redirect links for staking

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/bro_site#12]
Right in ussie comment

**Comment by bro-n-bro-2** [comment]
Bostrom - https://wallet.keplr.app/#/bostrom/stake?modal=detail&chainId=bostrom&validator=bostromvaloper1ydc5fy9fjdygvgw36u49yj39fr67pd9m5qexm8

Crescent - https://ping.pub/crescent/staking/crevaloper1c96vvme4k42zlvkc56fslmdpa2qj6u80xvqwau

Evmos - https://wallet.keplr.app/#/evmos/stake?modal=detail&chainId=evmos_9001-2&validator=evmosvaloper1ce4vh0e5kanlgc7z0rhcemvd8erjnfzcyfecl7

E-money - https://wallet.keplr.app/#/emoney/stake?modal=detail&chainId=emoney-3&validator=emoneyvaloper149vyxd36kxpg46rralaw6eejv4d9daqc3nv642

Gravity - https://wallet.keplr.app/#/gravity-bridge/stake?modal=detail&chainId=gravity-bridge-3&validator=gravityvaloper1vyd4k5j636erx5y5kdqghdu3rfjtwc48vdc7r6

Juno - https://wallet.keplr.app/#/juno/stake?modal=detail&chainId=juno-1&validator=junovaloper1quqxfrxkycr0uzt4yk0d57tcq3zk7srm7sm6r8

Microtick - https://microtick.ezstaking.io/validators/microvaloper13mkjrr578sxd7whex3mqru96vdt3tttw63uwtd

Omniflix -

Osmosis - https://wallet.keplr.app/#/osmosis/stake?modal=detail&chainId=osmosis-1&validator=osmovaloper13tk45jkxgf7w0nxquup3suwaz2tx483xe832ge

Stargaze - https://wallet.keplr.app/#/stargaze/stake?modal=detail&chainId=stargaze-1&validator=starsvaloper1y58hfnm90r4efhlydx0gavz57lvm7k6uulkg3h
