### ISSUE TITLE
Update links for staking to Keplr

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_site#49]
Osmosis: https://wallet.keplr.app/?tab=staking&modal=validator&chain=osmosis-1&validator_address=osmovaloper13tk45jkxgf7w0nxquup3suwaz2tx483xe832ge

Cosmos: https://wallet.keplr.app/chains/cosmos-hub?modal=validator&chain=cosmoshub-4&validator_address=cosmosvaloper106yp7zw35wftheyyv9f9pe69t8rteumjrx52jg

Juno: https://wallet.keplr.app/chains/juno?modal=validator&chain=juno-1&validator_address=junovaloper1quqxfrxkycr0uzt4yk0d57tcq3zk7srm7sm6r8

Evmos: https://wallet.keplr.app/chains/evmos?modal=validator&chain=evmos_9001-2&validator_address=evmosvaloper1ce4vh0e5kanlgc7z0rhcemvd8erjnfzcyfecl7

Stargaze: https://wallet.keplr.app/chains/stargaze?modal=validator&chain=stargaze-1&validator_address=starsvaloper1y58hfnm90r4efhlydx0gavz57lvm7k6uulkg3h

Bostrom: https://wallet.keplr.app/chains/bostrom?modal=validator&chain=bostrom&validator_address=bostromvaloper1ydc5fy9fjdygvgw36u49yj39fr67pd9m5qexm8

Gravity: https://wallet.keplr.app/chains/gravity-bridge?modal=validator&chain=gravity-bridge-3&validator_address=gravityvaloper1vyd4k5j636erx5y5kdqghdu3rfjtwc48vdc7r6

Stride: https://wallet.keplr.app/chains/stride?modal=validator&chain=stride-1&validator_address=stridevaloper1hl95uhecs4rwe0g432mknz2tsl84f0ltexpzc3

Omniflix: https://wallet.keplr.app/chains/omniflix?modal=validator&chain=omniflixhub-1&validator_address=omniflixvaloper1e8grpphncncw9hrutyvnlv77n5dejwcne58zk4

Desmos: https://ping.pub/desmos/staking/desmosvaloper1sykf8q94l8q8mqstf64ptuvp74ueyehxpgcq76

**Comment by prevetal** [comment]
don't have link for Crescent hub

**Comment by bro-n-bro-2** [comment]
Crescent : https://ping.pub/crescent/staking/crevaloper1c96vvme4k42zlvkc56fslmdpa2qj6u80xvqwau
