### ISSUE TITLE
Happy New Year decoration

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_site#50]
Happy New Year decoration
- website
- TG
- twitter
- posts

**Comment by irahunt** [comment]
![avatar](https://github.com/bro-n-bro/bro_site/assets/106156987/a8aa8dfe-a1fd-4028-a9d4-3fbf784353e8)
![twitter_header_2x](https://github.com/bro-n-bro/bro_site/assets/106156987/a350695e-35aa-4536-87a9-23a9a9d71c96)

**Comment by irahunt** [comment]
https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=7979-111091&mode=design&t=qSKUhpjhxLBhCL99-4


@prevetal

**Comment by bro-n-bro-99** [comment]
twitter updated
