### ISSUE TITLE
add Nomic dash to the Validated networks

### ISSUE THREAD

**Issue by bro-n-bro-99** [bro-n-bro/bro_site#52]
logo - https://pbs.twimg.com/profile_images/1706799057698541568/lXkr_Cm1_400x400.jpg

delegation link - https://app.nomic.io/staking?validator=nomic137gur62zxm5ydpxs3mqzxytqgnp2gdkzglh76s&modal=info

**Comment by bro-n-bro-2** [comment]
![image](https://github.com/bro-n-bro/bro_site/assets/89855562/43c1fed2-4f07-432d-9125-a328e96645b7)

**Comment by bro-n-bro-99** [comment]
@prevetal description for Nomic - Nomic is a layer-1 blockchain which offers a decentralized, non-custodial Bitcoin bridge.
