### ISSUE TITLE
Add Dymension to website

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_site#59]
Add Dymension to website

**Comment by prevetal** [comment]
I need url for the "Stake with your bro" button.

**Comment by bro-n-bro-2** [comment]
https://wallet.keplr.app/?tab=staking&modal=validator&chain=dymension_1100-1&validator_address=dymvaloper1tvn903vynfslcfy5jvwt2n667vunx4y8qxrsf5

**Comment by bro-n-bro-99** [comment]
@prevetal 
description - Powering the Internet of RollApps
logo - https://pbs.twimg.com/profile_images/1663159896701820928/by0GLREA_400x400.jpg
