### ISSUE TITLE
Design bro landing page

### ISSUE THREAD

**Issue by bro-n-bro-0** [bro-n-bro/bro_site#6]
It should contain 

- Home
- Whoami
- Validated networks 
- Coming soon networks
- Contributions
- cyber Blog
- Contacts 

It's possible to use https://bro-n-bro.github.io/bro_site/

For each network add the Delegate button. It should forward to the delegation window of the chosen network. 

The design have to be in bro_site repo

**Comment by irahunt** [comment]
Figma: https://clck.ru/q75Lc
