### ISSUE TITLE
Create new picture to align with new stats

### ISSUE THREAD

**Issue by bro-n-bro-2** [bro-n-bro/bro_site#61]
![image](https://github.com/bro-n-bro/bro_site/assets/89855562/e4409c4d-6115-41c1-aba4-bd0c36c26728)

**Comment by irahunt** [comment]
@prevetal https://www.figma.com/file/qhmlIKVNDNUFfdkOZqhvnR/%F0%9F%91%8A%F0%9F%8F%BB-bro_n_bro-team?type=design&node-id=2884-14673&mode=design&t=fZtU8ELBvxOUpEp8-4

**Comment by bro-n-bro-2** [comment]
update link as well to https://stats.bronbro.io/
